### ISSUE TITLE
Greek characters are not forwarded correctly

### ISSUE THREAD

**Issue by ProteusCortex** [ProteusCortex/kow-whois#2]
When searching for a domain containing Greek characters (e.g. `δρακουμ.ελ`) an error `400` is returned like so:

```
Request failed with status code 400
Error: Request failed with status code 400
    at createError (/usr/src/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/src/app/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/usr/src/app/node_modules/axios/lib/adapters/http.js:201:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by Petr0s92** [comment]
https://www.punycoder.com/

**Comment by stathis** [comment]
Good code.
